#!/usr/bin/env python3
"""
How often does a hand-typed unit conversion in print fail to close?

The claim I have been making all week, from two anecdotes: error does not live in
the calculation, it lives at the seam where a calculation becomes a printed thing.
Two anecdotes is not a rate. This gets a rate.

THE INSTRUMENT
  A dual-unit statement -- "5 miles (8 km)" -- is a calculation whose inputs and
  output are both printed on the page. It is checkable with no domain knowledge.
  Wikipedia wikitext lets me separate two populations that render identically:

    CONTROL   {{convert|5|mi|km}}   -- generated by software, cannot slip
    TREATMENT 5 miles (8 km)        -- typed by a person

  The control is the gate. It is a population known to be right. If this checker
  flags control pairs as wrong, the checker is broken and no verdict it gives on
  the treatment group means anything. That is the whole design: validate the
  detector against a known state BEFORE it is allowed to say anything new.

THE TEST IS INTERVAL ARITHMETIC, NOT EQUALITY
  "5 miles" is a rounded number: it stands for [4.5, 5.5). "8 km" stands for
  [7.5, 8.5). The honest question is not "does 5 mi equal 8 km" -- it is
  "can the two intervals be talking about the same quantity?" If converting the
  source interval produces a range that overlaps the printed target interval,
  the statement closes. Only a total failure to overlap is a mismatch.

  This is deliberately conservative. It will miss real sloppiness. It will not
  manufacture errors out of rounding, which is the failure mode that would make
  the resulting rate a lie.

Iris (Opus 4.8, 1M) -- fire 142, Jul 19 2026.
"""

import hashlib
import json
import os
import re
import sys
import time
import urllib.parse
import urllib.request
from decimal import Decimal

UA = ("iris-seam-check/1.1 (transcription-seam study; "
      "https://github.com/savecharlie/recomputed)")

# Floor between API requests. The en.wikipedia API edge (Envoy) publishes
# `retry-after: 3` on its 429s; anything under that never escapes the refusal
# window, because an early request keeps the bucket empty. Measured fire 144.
REQ_SPACING = 4.0

# ---------------------------------------------------------------- units
# factor = how many BASE units in one of these. Pairs are only compared
# within the same dimension.
UNITS = {
    # length (base: metre)
    "mi": ("L", Decimal("1609.344")), "mile": ("L", Decimal("1609.344")),
    "miles": ("L", Decimal("1609.344")),
    "km": ("L", Decimal("1000")), "kilometre": ("L", Decimal("1000")),
    "kilometres": ("L", Decimal("1000")), "kilometer": ("L", Decimal("1000")),
    "kilometers": ("L", Decimal("1000")),
    "m": ("L", Decimal("1")), "metre": ("L", Decimal("1")),
    "metres": ("L", Decimal("1")), "meter": ("L", Decimal("1")),
    "meters": ("L", Decimal("1")),
    "ft": ("L", Decimal("0.3048")), "foot": ("L", Decimal("0.3048")),
    "feet": ("L", Decimal("0.3048")),
    "yd": ("L", Decimal("0.9144")), "yard": ("L", Decimal("0.9144")),
    "yards": ("L", Decimal("0.9144")),
    "in": ("L", Decimal("0.0254")), "inch": ("L", Decimal("0.0254")),
    "inches": ("L", Decimal("0.0254")),
    "cm": ("L", Decimal("0.01")), "centimetre": ("L", Decimal("0.01")),
    "centimetres": ("L", Decimal("0.01")), "centimeters": ("L", Decimal("0.01")),
    "mm": ("L", Decimal("0.001")),
    "nmi": ("L", Decimal("1852")),
    # mass (base: kilogram)
    "kg": ("M", Decimal("1")), "kilogram": ("M", Decimal("1")),
    "kilograms": ("M", Decimal("1")),
    "lb": ("M", Decimal("0.45359237")), "lbs": ("M", Decimal("0.45359237")),
    "pound": ("M", Decimal("0.45359237")), "pounds": ("M", Decimal("0.45359237")),
    "g": ("M", Decimal("0.001")), "gram": ("M", Decimal("0.001")),
    "grams": ("M", Decimal("0.001")),
    "oz": ("M", Decimal("0.028349523125")), "ounce": ("M", Decimal("0.028349523125")),
    "ounces": ("M", Decimal("0.028349523125")),
    "t": ("M", Decimal("1000")), "tonne": ("M", Decimal("1000")),
    "tonnes": ("M", Decimal("1000")),
    # area (base: square metre)
    "acre": ("A", Decimal("4046.8564224")), "acres": ("A", Decimal("4046.8564224")),
    "ha": ("A", Decimal("10000")), "hectare": ("A", Decimal("10000")),
    "hectares": ("A", Decimal("10000")),
    # speed (base: m/s)
    "mph": ("S", Decimal("0.44704")),
    "km/h": ("S", Decimal("1") / Decimal("3.6")),
    "kph": ("S", Decimal("1") / Decimal("3.6")),
    "kn": ("S", Decimal("0.514444")), "knots": ("S", Decimal("0.514444")),
    # volume (base: litre)
    "l": ("V", Decimal("1")), "litre": ("V", Decimal("1")),
    "litres": ("V", Decimal("1")), "liter": ("V", Decimal("1")),
    "liters": ("V", Decimal("1")),
    "ml": ("V", Decimal("0.001")),
    "impgal": ("V", Decimal("4.54609")),
}

NUM = r"\d{1,3}(?:,\d{3})+(?:\.\d+)?|\d+(?:\.\d+)?"
UNIT_ALT = "|".join(sorted((re.escape(u) for u in UNITS), key=len, reverse=True))
# Wikipedia's house style puts a non-breaking space between number and unit:
# "6&nbsp;ft". That is not \s, and treating it as ordinary text made this
# instrument silently blind to most hand-typed pairs in the corpus -- a false
# zero produced by a regex, which is precisely the failure mode I keep warning
# myself about. Found by printing what the matcher actually saw.
SEP = r"(?:\s|&nbsp;|&#160;|&#xA0;|\u00a0)*"

# "12,345 feet (3,763 m)" -- the source, then the conversion in parentheses.
PAIR_RE = re.compile(
    rf"(?P<a_num>{NUM}){SEP}(?P<a_unit>{UNIT_ALT})\b"
    rf"[^()\n]{{0,14}}?\({SEP}(?P<b_num>{NUM}){SEP}(?P<b_unit>{UNIT_ALT})\b{SEP}\)",
    re.IGNORECASE,
)

CONVERT_RE = re.compile(r"\{\{\s*(?:convert|cvt)\s*\|", re.IGNORECASE)

# "6 ft 3 inch (1.91 m)" is a COMPOUND measurement: six feet three inches, which
# is 1.905 m and perfectly correct. A regex that grabs only "3 inch (1.91 m)"
# reports a 25x error that isn't there. This cost me my only "finding" in the
# first full run, and it is the exact failure this project is about -- an
# instrument that is confidently wrong about an input it mis-identified.
COMPOUND_RE = re.compile(rf"(?:{NUM}){SEP}(?:{UNIT_ALT})\b{SEP}$", re.IGNORECASE)


FRACTION_RE = re.compile(r"/\s*$")


def is_compound(text, match_start):
    """True if the match is only a FRAGMENT of the quantity actually written.

    Two ways that happens, both found by hand-checking flags rather than by
    thinking about it:
      "6 ft 3 inch (1.91 m)"    -> matching from '3 inch' reports a 25x error
      "1 1/8 in thick (28 mm)"  -> matching from '8 in' reports a 7x error
    Both are correct on the page. Both would have been my only 'findings'.
    """
    pre = text[max(0, match_start - 30):match_start]
    return bool(COMPOUND_RE.search(pre) or FRACTION_RE.search(pre))


def parse_num(s):
    return Decimal(s.replace(",", ""))


def rounding_interval(s):
    """The half-open interval a printed decimal literal stands for.

    "8"     -> [7.5, 8.5)      "8.0" -> [7.95, 8.05)
    "1,200" -> [1199.5, 1200.5)   -- I do NOT assume trailing zeros are
                                     insignificant; that would silently widen
                                     every round number and hide real errors.
    """
    t = s.replace(",", "")
    if "." in t:
        places = len(t.split(".")[1])
        half = Decimal(1).scaleb(-places) / 2
    else:
        half = Decimal("0.5")
    v = Decimal(t)
    return v - half, v + half


# A person who writes "70 mph (110 km/h)" has not made a mistake in the sense I
# am hunting. 70 mph is 112.7 km/h; they rounded to a comfortable number and
# every reader understands that. A person who writes "5 miles (80 km)" has done
# something categorically different. A strict interval test cannot tell those
# apart, so it does not get to call both of them errors.
#
#   CLOSES    the rounding intervals overlap. Nothing to see.
#   LOOSE     they don't overlap, but the printed value is within 10% of true.
#             Deliberate rounding, house style, or mild sloppiness. NOT counted.
#   MISMATCH  off by more than 10%. This is the population of interest.
#
# The 10% line is a judgement and I am stating it rather than burying it. It is
# set to be generous to the writer: it excuses every "about a hundred" in the
# corpus, at the cost of missing real errors smaller than a tenth. That trade is
# deliberate -- a rate that is too low is a boring result, and a rate inflated by
# counting ordinary rounding as error would be a lie.
LOOSE_BAND = Decimal("0.10")


def check_pair(a_num, a_unit, b_num, b_unit):
    """Return (verdict, detail). Verdict in CLOSES / LOOSE / MISMATCH / SKIP."""
    au, bu = a_unit.lower(), b_unit.lower()
    if au not in UNITS or bu not in UNITS:
        return "SKIP", "unknown unit"
    dim_a, fa = UNITS[au]
    dim_b, fb = UNITS[bu]
    if dim_a != dim_b:
        return "SKIP", "different dimensions"
    if au == bu:
        return "SKIP", "same unit"

    a_lo, a_hi = rounding_interval(a_num)
    b_lo, b_hi = rounding_interval(b_num)
    c_lo = a_lo * fa / fb
    c_hi = a_hi * fa / fb
    if not (c_hi <= b_lo or c_lo >= b_hi):
        return "CLOSES", ""

    exact = parse_num(a_num) * fa / fb
    if not exact:
        return "SKIP", "zero"
    ratio = parse_num(b_num) / exact
    if abs(ratio - 1) <= LOOSE_BAND:
        return "LOOSE", ""

    # name the shape of the failure -- these are the signatures I am hunting
    shape = "other"
    # "10 km (16 miles)": they multiplied by 1.609 instead of dividing by it.
    backwards = parse_num(a_num) * fb / fa
    if abs(ratio - 10) < Decimal("0.5") or abs(ratio - Decimal("0.1")) < Decimal("0.005"):
        shape = "factor of ten"
    elif abs(ratio - 100) < 5 or abs(ratio - Decimal("0.01")) < Decimal("0.0005"):
        shape = "factor of a hundred"
    elif backwards and abs(parse_num(b_num) / backwards - 1) <= LOOSE_BAND:
        shape = "conversion applied backwards"
    elif abs(ratio - 2) < Decimal("0.1") or abs(ratio - Decimal("0.5")) < Decimal("0.025"):
        shape = "factor of two"
    return "MISMATCH", {
        "printed": f"{a_num} {a_unit} ({b_num} {b_unit})",
        "should_be": f"{exact:.6g}",
        "ratio_printed_over_true": f"{ratio:.4f}",
        "shape": shape,
    }


# ---------------------------------------------------------------- gates
def gates():
    """The detector must survive these before any verdict of its own counts."""
    cases = [
        # (a, aunit, b, bunit, expected)
        # -- must CLOSE: ordinary correct rounded conversions
        ("5", "miles", "8", "km", "CLOSES"),
        ("1", "mile", "1.6", "km", "CLOSES"),
        ("100", "ft", "30", "m", "CLOSES"),
        ("29,032", "ft", "8,849", "m", "CLOSES"),      # Everest
        ("1", "acre", "0.40", "ha", "CLOSES"),
        ("200", "lb", "91", "kg", "CLOSES"),
        # -- must be LOOSE: a person rounding to a comfortable number.
        #    NOT an error. 70 mph is 112.7 km/h; I wrote this case expecting
        #    it to CLOSE and the detector was right and I was wrong, which is
        #    the reason the LOOSE band exists at all.
        ("70", "mph", "110", "km/h", "LOOSE"),
        ("26.2", "miles", "42", "km", "CLOSES"),   # and again: 42 km IS right
        # -- must be MISMATCH: the failure modes I am hunting
        ("5", "miles", "80", "km", "MISMATCH"),        # factor of ten
        ("5", "miles", "0.8", "km", "MISMATCH"),       # factor of ten, other way
        ("100", "ft", "300", "m", "MISMATCH"),         # decimal point moved
        ("10", "km", "16", "miles", "MISMATCH"),       # factor applied backwards
        ("124.77", "in", "0.9627", "m", "MISMATCH"),   # tonight's shape, in units
        ("50", "kg", "50", "lb", "MISMATCH"),          # 50 kg is 110 lb
        # -- must SKIP, not crash
        ("5", "miles", "8", "kg", "SKIP"),
    ]
    print("── gates (the detector must pass these before it may accuse anyone) ──")
    ok = True
    for a, au, b, bu, want in cases:
        got, detail = check_pair(a, au, b, bu)
        good = got == want
        ok &= good
        shape = f"  [{detail['shape']}]" if isinstance(detail, dict) else ""
        print(f"  [{'PASS' if good else 'FAIL'}] {a} {au} ({b} {bu}) -> "
              f"{got:8s} want {want}{shape}")
    print()
    return ok


# ---------------------------------------------------------------- corpus
# Random Wikipedia is mostly stubs about villages and beetles: 40 articles gave
# me one checkable pair. The seam only exists where people write measurements, so
# the corpus is drawn from categories that are dense in them. This is a biased
# sample OF WIKIPEDIA and I am not pretending otherwise -- but it is not biased
# toward errors, which is the bias that would matter. I chose these categories
# for measurement density, before seeing a single result.
CATEGORIES = [
    "Category:Mountains of the United States",
    "Category:Rivers of England",
    "Category:Bridges in New York City",
    "Category:Lakes of Canada",
    "Category:Skyscrapers in Chicago",
    "Category:Dams in California",
    "Category:Volcanoes of Japan",
    "Category:Roads in Scotland",
    "Category:Caves of France",
    "Category:Islands of Norway",
    "Category:Waterfalls of Norway",
    "Category:Ocean liners",
    "Category:Steam locomotives of Great Britain",
    "Category:Airships",
    "Category:Nature reserves in England",
    "Category:Canals in England",
    "Category:Lighthouses in Scotland",
    "Category:Mountains of Switzerland",
    "Category:Rivers of India",
    "Category:Bridges in Japan",
    "Category:Reservoirs in Wales",
    "Category:Glaciers of Alaska",
    "Category:Sailing ships",
    "Category:Tunnels in Norway",
    "Category:Peaks of the Rocky Mountains",
    "Category:Lakes of Finland",
    "Category:Deserts of Australia",
    "Category:Windmills in the Netherlands",
    "Category:Railway stations in India",
    "Category:Cathedrals in France",
    # --- fire 143: corpus widened to tighten the interval on the treatment rate.
    # The DETECTOR is unchanged (check_pair, the gates, the interval arithmetic are
    # byte-identical). Only the sample is larger. Widening a sample after seeing a
    # result is not the same sin as tuning a threshold after seeing a result: the
    # thing that decides pass/fail did not move, and the direction the number will
    # travel is not knowable in advance.
    "Category:Mountains of Austria",
    "Category:Rivers of Scotland",
    "Category:Bridges in Germany",
    "Category:Lakes of Sweden",
    "Category:Skyscrapers in New York City",
    "Category:Dams in India",
    "Category:Volcanoes of Chile",
    "Category:Roads in Wales",
    "Category:Caves of the United States",
    "Category:Islands of Scotland",
    "Category:Waterfalls of the United States",
    "Category:Cargo ships",
    "Category:Steam locomotives of Germany",
    "Category:Airliners",
    "Category:National parks of Canada",
    "Category:Canals in France",
    "Category:Lighthouses in Norway",
    "Category:Mountains of Italy",
    "Category:Rivers of Russia",
    "Category:Bridges in China",
    "Category:Reservoirs in Scotland",
    "Category:Glaciers of Switzerland",
    "Category:Submarines",
    "Category:Tunnels in Switzerland",
    "Category:Mountains of Colorado",
    "Category:Lakes of Norway",
    "Category:Deserts of Africa",
    "Category:Castles in Wales",
    "Category:Railway stations in Germany",
    "Category:Cathedrals in England",
]


def wiki_category_titles(n):
    """Article titles from measurement-dense categories, round-robin."""
    per_cat = {}
    dropped = []
    for cat in CATEGORIES:
        # The sleep goes BEFORE the request, not after. It used to sit at the end
        # of the loop body, where `continue` skipped it -- so the instant a
        # category 429'd, the next one was fired with no delay at all. A rate
        # limit producing MORE requests is a positive feedback loop, and it
        # silently shrank the corpus while printing a line that looked like a
        # harmless note. Same family as the &nbsp; bug: a quiet under-count that
        # comes back looking fine. (fire 143)
        #
        # 2.0 was the bug. The API edge publishes `retry-after: 3`, so 2.0 sat
        # permanently inside the refusal window and 429'd all sixty categories.
        # Measured fire 144: 4.0s spacing -> 6/6 requests 200. fetch_json now
        # honors Retry-After as well, so this is the floor, not the safety net.
        time.sleep(REQ_SPACING)
        url = ("https://en.wikipedia.org/w/api.php?action=query&format=json"
               "&list=categorymembers&cmnamespace=0&cmlimit=500&cmtitle="
               + urllib.parse.quote(cat))
        try:
            members = fetch_json(url)["query"]["categorymembers"]
        except Exception as e:
            print(f"  (category {cat} failed: {e})", file=sys.stderr)
            dropped.append(cat)
            continue
        per_cat[cat] = [m["title"] for m in members]
    if dropped:
        # A dropped category is not a cosmetic loss -- it is a sample that is not
        # the sample I say it is. Say so loudly rather than reporting a rate over
        # a corpus quietly different from the described one.
        print(f"  !! {len(dropped)}/{len(CATEGORIES)} categories DROPPED: "
              f"{', '.join(c.replace('Category:', '') for c in dropped)}", file=sys.stderr)
    # round-robin so no single category dominates the sample
    titles, i = [], 0
    while len(titles) < n and any(len(v) > i for v in per_cat.values()):
        for v in per_cat.values():
            if len(v) > i and len(titles) < n:
                titles.append(v[i])
        i += 1
    print(f"  drew from {len(per_cat)} categories")
    return titles[:n]


def fetch_json(url, tries=8):
    """Fetch, letting the SERVER set the pace.

    Fire 143 diagnosed the 429 storm as "Wikipedia is rate-limiting hard" and
    queued the fix "back off harder." Both were guesses. Fire 144 read the whole
    refusal instead of its status line:

        HTTP/2 429
        x-envoy-ratelimited: true
        retry-after: 3

    The number was in the response the entire time, in a header named
    `Retry-After`, and the loop was sleeping 2.0 -- one second short, forever.
    A request arriving inside the window doesn't merely get refused, it keeps
    the bucket empty, so a too-fast caller 429s on EVERY request and it looks
    identical to a permanent IP block. (It looked exactly like that: sixty of
    sixty categories, hours after the previous run, even on an empty
    `meta=siteinfo` query.)

    So: no guessed constant. Obey `Retry-After` when it is sent; fall back to
    exponential backoff only when it isn't. A constant that happens to clear a
    published threshold is a fix that breaks silently the day they change it.
    """
    delay = 2.0
    for attempt in range(tries):
        req = urllib.request.Request(url, headers={"User-Agent": UA})
        try:
            with urllib.request.urlopen(req, timeout=60) as r:
                return json.loads(r.read().decode("utf-8"))
        except urllib.error.HTTPError as e:
            if e.code in (429, 503) and attempt < tries - 1:
                # The server's own number wins over anything I would pick.
                ra = e.headers.get("Retry-After") if e.headers else None
                try:
                    wait = float(ra) + 0.5
                except (TypeError, ValueError):
                    wait = delay
                    delay *= 2
                time.sleep(wait)
                continue
            raise
    raise RuntimeError("unreachable")


CACHE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "cache")


def cached_wikitext(titles):
    """Fetch, but never fetch the same article twice across runs."""
    os.makedirs(CACHE, exist_ok=True)
    out, missing = {}, []
    for tt in titles:
        fn = os.path.join(CACHE, hashlib.sha1(tt.encode()).hexdigest() + ".txt")
        if os.path.exists(fn):
            out[tt] = open(fn, encoding="utf-8").read()
        else:
            missing.append(tt)
    if missing:
        print(f"  {len(out)} cached, fetching {len(missing)}…")
        fresh = fetch_wikitext(missing)
        for tt, wt in fresh.items():
            fn = os.path.join(CACHE, hashlib.sha1(tt.encode()).hexdigest() + ".txt")
            with open(fn, "w", encoding="utf-8") as fh:
                fh.write(wt)
        out.update(fresh)
    return out


def fetch_wikitext(titles):
    """Up to 50 titles per call. Returns {title: wikitext}."""
    out = {}
    for i in range(0, len(titles), 25):
        chunk = titles[i:i + 25]
        url = ("https://en.wikipedia.org/w/api.php?action=query&format=json"
               "&prop=revisions&rvprop=content&rvslots=main&titles="
               + urllib.parse.quote("|".join(chunk)))
        try:
            data = fetch_json(url)
        except Exception as e:
            print(f"  (fetch failed for a chunk: {e})", file=sys.stderr)
            continue
        for page in data.get("query", {}).get("pages", {}).values():
            try:
                out[page["title"]] = page["revisions"][0]["slots"]["main"]["*"]
            except (KeyError, IndexError):
                pass
        # Was 1.0 -- inside the published 3s refusal window, same bug as the
        # category loop. Every chunk boundary was a coin-flip on a 429 that
        # `continue` then swallowed as a silently missing 25 articles.
        time.sleep(REQ_SPACING)
    return out


def strip_convert_templates(text):
    """Remove {{convert|...}} / {{cvt|...}} calls, brace-balanced.

    Everything left is a dual-unit pair a human typed. Returns
    (text_without_templates, number_of_templates_removed).
    """
    out = []
    i = 0
    removed = 0
    while True:
        m = CONVERT_RE.search(text, i)
        if not m:
            out.append(text[i:])
            break
        out.append(text[i:m.start()])
        depth = 0
        j = m.start()
        while j < len(text):
            if text.startswith("{{", j):
                depth += 1
                j += 2
            elif text.startswith("}}", j):
                depth -= 1
                j += 2
                if depth == 0:
                    break
            else:
                j += 1
        removed += 1
        i = j
    return "".join(out), removed


def render_convert_templates(text):
    """Turn {{convert|A|unitA|unitB}} into 'A unitA (B unitB)' as the template
    itself would -- but computing B correctly. Used to build the CONTROL group:
    pairs that are right by construction. If the checker flags these, it is broken.
    """
    pairs = []
    for m in re.finditer(r"\{\{\s*(?:convert|cvt)\s*\|([^{}]*)\}\}", text, re.IGNORECASE):
        parts = [p.strip() for p in m.group(1).split("|")]
        if len(parts) < 3:
            continue
        a_num, a_unit, b_unit = parts[0], parts[1], parts[2]
        if not re.fullmatch(NUM, a_num):
            continue
        au, bu = a_unit.lower(), b_unit.lower()
        if au not in UNITS or bu not in UNITS or UNITS[au][0] != UNITS[bu][0]:
            continue
        exact = parse_num(a_num) * UNITS[au][1] / UNITS[bu][1]
        # the template rounds to comparable precision; emulate with 3 s.f.
        b_num = f"{exact:.3g}"
        pairs.append((a_num, a_unit, b_num, b_unit))
    return pairs


def main():
    if not gates():
        raise SystemExit("gates failed — the detector is not trustworthy, no verdict given")

    n = int(sys.argv[1]) if len(sys.argv) > 1 else 400
    print(f"── corpus: up to {n} English Wikipedia articles, measurement-dense categories ──")
    titles = wiki_category_titles(n)
    pages = cached_wikitext(titles)
    print(f"  fetched wikitext for {len(pages)} articles\n")

    control = {"CLOSES": 0, "LOOSE": 0, "MISMATCH": 0, "SKIP": 0}
    treat = {"CLOSES": 0, "LOOSE": 0, "MISMATCH": 0, "SKIP": 0}
    findings = []
    n_templates = 0
    n_compound = 0

    for title, text in pages.items():
        # CONTROL: pairs the software generated
        for a, au, b, bu in render_convert_templates(text):
            v, _ = check_pair(a, au, b, bu)
            control[v] += 1

        # TREATMENT: what a person typed, with the templates cut out first
        human_text, removed = strip_convert_templates(text)
        n_templates += removed
        for m in PAIR_RE.finditer(human_text):
            if is_compound(human_text, m.start()):
                treat["SKIP"] += 1
                n_compound += 1
                continue
            v, detail = check_pair(m.group("a_num"), m.group("a_unit"),
                                   m.group("b_num"), m.group("b_unit"))
            treat[v] += 1
            if v == "MISMATCH":
                ctx = human_text[max(0, m.start() - 90):m.end() + 90].replace("\n", " ")
                findings.append({"article": title, "detail": detail, "context": ctx})

    def rate(d):
        n = d["CLOSES"] + d["LOOSE"] + d["MISMATCH"]
        return (100.0 * d["MISMATCH"] / n) if n else float("nan"), n

    c_rate, c_n = rate(control)
    t_rate, t_n = rate(treat)

    print("── CONTROL: conversions generated by {{convert}} ──")
    print(f"  {c_n} checkable pairs, {control['MISMATCH']} flagged  ->  {c_rate:.2f}%")
    print("  (this is the gate. it must be ~0. any flag here is MY bug, not Wikipedia's.)\n")
    print("── TREATMENT: conversions typed by a person ──")
    print(f"  {t_n} checkable pairs, {treat['MISMATCH']} flagged  ->  {t_rate:.2f}%\n")
    print(f"  ({n_templates} convert-templates removed before scanning the human text;")
    print(f"   {n_compound} compound measurements like '6 ft 3 in (1.91 m)' skipped)")

    if findings:
        print("\n── every mismatch, so it can be checked by hand ──")
        for f in findings:
            print(f"\n  {f['article']}")
            print(f"    printed : {f['detail']['printed']}")
            print(f"    true    : {f['detail']['should_be']} "
                  f"(printed/true = {f['detail']['ratio_printed_over_true']})")
            print(f"    context : …{f['context'].strip()[:180]}…")

    out = {
        "control": control, "treatment": treat,
        "control_rate_pct": c_rate, "treatment_rate_pct": t_rate,
        "articles": len(pages), "findings": findings,
    }
    with open("seam_result.json", "w") as fh:
        json.dump(out, fh, indent=2, default=str)
    print("\nwrote seam_result.json")


if __name__ == "__main__":
    main()
